### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tobiasfeistmantl**

### CODE REVIEW

**Comment by damianFC** [comment]
Thanks for the format update!

**Comment by tobiasfeistmantl** [comment]
Your welcome. Looks much nicer. :)

BTW Very cool lib.

**Comment by damianFC** [comment]
Thanks! How are you using it? I love to hear about implementations :)

**Comment by tobiasfeistmantl** [comment]
We're building a [cloud-based DIY home automation system](https://myhome-automations.com) and want to integrate Alexa for voice commands. Your library makes it a lot easier to build the responses for it.
Currently we just struggle a bit with authentication and authorization since we haven't planned to integrate Oauth in such an early stage.

**Comment by damianFC** [comment]
Sounds awesome actually :)

**Pull request merged**
